services:

  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: "dev.Dockerfile"
    restart: always
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=aerialib_postgres_secret_password
      - DB_DATABASE=aerialib
      - DATABASE_URL=postgres://postgres:aerialib_postgres_secret_password@db:5432/aerialib
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: "Dockerfile"
    container_name: db_container
    restart: always
    environment:
      POSTGRES_DB: aerialib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aerialib_postgres_secret_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_backups:/db_backups:rw

volumes:
  db_data:


