FROM postgres:latest
# TODO IMPLEMENT PROPERLY
# RUN apt-get update && apt-get install -y cron
# COPY backup.sh /usr/local/bin/backup.sh
# RUN chmod +x /usr/local/bin/backup.sh
# # Set up cron to run the script (e.g., daily)
# CMD (crontab -l 2>/dev/null; echo "0 0 * * * /usr/local/bin/backup.sh") | crontab -
# VOLUME /backups